version: '3.2'
services:
  web:
    build: 
      context: ./node
    volumes:
      - type: bind
        source: ./code
        target: /usr/src/app/code
    ports:
      - "49160:8080"
    command: nodemon tutorial/hello.js